-- AlterTable
ALTER TABLE "user" ALTER COLUMN "btc" SET DATA TYPE BIGINT,
ALTER COLUMN "eth" SET DATA TYPE BIGINT,
ALTER COLUMN "matic" SET DATA TYPE BIGINT,
ALTER COLUMN "total_in_usdt" SET DATA TYPE BIGINT,
ALTER COLUMN "usdt" SET DATA TYPE BIGINT;
